### ISSUE TITLE
Can you confirm this is still working?

### ISSUE THREAD

**Issue by apexmateria** [OpenAff/geoip-js#2]
I'm located in Canada and it sent me to domain.com instead of domain.ca

**Comment by irazasyed** [comment]
Hi,

Unfortunately, This script is depended on MaxMind's GeoIP JS API and they no longer providing access to their JS API for free (They used to provide and now removed). Due to which, The script is broken for now.

I'll look around for some other API that's available online and update the script soon.

Thanks!

**Comment by apexmateria** [comment]
That would be awesome, thanks my friend!

**Comment by irazasyed** [comment]
@apexmateria No problem. I've updated the script with the new API. Feel free to try and report back if any issues!

**Comment by apexmateria** [comment]
You're the man! That's so much for fixing it so quickly. It works perfectly now :+1:

**Comment by irazasyed** [comment]
Cool :+1:

**Comment by djmedinan** [comment]
Any geoapi update?
